name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run application import test
        run: python -c "from app.app import app; print('Application import successful')"
    
  security:
    name: Security scan
    runs-on: ubuntu-latest

    steps:
       - name: Checkout Repository
         uses: actions/checkout@v4
       - name: Build container image
         run: podman build -t cloud-native-platform-app:ci .

       - name: Install Trivy
         uses: aquasecurity/trivy-action@v0.2.4

       - name: Scan container image
         run: trivy image --severity HIGH,CRITICAL --exit-code 1 cloud-native-platform-app:ci 
